package hello.hellospring.domain;


import javax.persistence.*;

@Entity
public class Member {

    // H2 db sql문
//    drop table if exists member CASCADE;
//    create table member
//            (
//                    id bigint generated by default as identity, //id 생성
//                    name varchar(255), // name 생성
//    primary key(id)
//    );
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)//jpa 제공 sequence 와 같음
    private Long id;

    private String name;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
