-- H2 db sql문 테이블 생성문
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,/*id 생성*/
    name varchar(255),/*name 생성*/
    primary key(id)
);

-- 멤버 테이블 조회
SELECT * FROM MEMBER;

-- 컬럼 삽입
insert into member(name) values('spring');